name: Deploy to remote EC2 server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.EC2_DNS }}
          username: ${{ secrets.EC2_USER }}
          privateKey: ${{ secrets.EC2_KEY }}
        #run: ssh -i ${{ secrets.EC2_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_DNS }} './deployScript.sh aws-rds-connection'

