name: Deploy to remote EC2 server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.EC2_DNS }}
        host: ec2-13-38-93-128.eu-west-3.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          ls
